import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  text: {
    fontSize: 24,
    fontWeight: "500",
    textAlign: "center",
    paddingHorizontal: 5,
  },
  button: {
    textAlign: "center",
    margin: 10,
    padding: 10,
    backgroundColor: "#DDDDDD",
  },
  textButton: {
    fontSize: 16,
    fontWeight: "700",
  },
  smallText: {
    fontSize: 16,
    fontWeight: "500",
  },
  backgroundVideo: {
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
  video: {
    alignSelf: "center",
    width: 320,
    height: 200,
    marginBottom: 20,
  },
  buttons: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  fixToText: {
    flexDirection: "row",
    justifyContent: "center",
  },
  button: {
    alignItems: "center",
    backgroundColor: "#add8e6",
    padding: 10,
    width: 100,
    marginTop: 0,
    marginRight: 5,
    marginLeft: 5,
    borderRadius: 4,
  },
  buttonHome: {
    alignItems: "center",
    backgroundColor: "#add8e6",
    padding: 10,
    width: 100,
    marginTop: 0,
    marginRight: 5,
    marginLeft: 5,
    borderRadius: 4,
    marginBottom: 20,
  },
  text: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 20,
  },
  textBottom: {
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  applyBtn: {
    backgroundColor: "#16f083",
    alignItems: "center",
    padding: 10,
    width: 210,
    marginLeft: 5,
    marginRight: 5,
    borderRadius: 4,
    marginLeft: "auto",
    marginRight: "auto",
    flexDirection: "row",
    justifyContent: "center",
  },
  pickBtn: {
    backgroundColor: "#16f083",
    alignItems: "center",
    padding: 10,
    width: 210,
    marginLeft: 5,
    marginRight: 5,
    marginBottom: 5,
    borderRadius: 4,
    marginLeft: "auto",
    marginRight: "auto",
    flexDirection: "row",
    justifyContent: "center",
  },
  applyText: {
    fontSize: 16,
    fontWeight: "600",
    color: "white",
  },
});
